import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  background: {
    position: "relative",
    height: "100%",
  },
  imgbg: {
    position: "absolute",
    top: "4%",
    width: "250%",
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
  },
  container: {
    flex: 1,
    backgroundColor: "#EECCD7",
  },
  filtroNovoJogo: {
    flexDirection: "row",
    backgroundColor: "#FF3276",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    paddingVertical: 4,
    paddingHorizontal: 12,
  },
  filtros: {
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#FF3276",
    backgroundColor: "#EECCD7",
  },
  textFiltros: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "500",
  },
  jogosText: {
    color: "#fff",
    fontSize: 24,
    fontWeight: "500",
  },
  botaoAdd: {
    backgroundColor: "#EECCD7",
    justifyContent: "center",
    alignItems: "center",
    padding: 10,
    borderRadius: 8,
    width: 110,
  },
  textAdd: {
    textAlign: "center",
    fontSize: 16,
    color: "#FF3276",
    fontWeight: "bold",
  },
  filtroContainer: {
    flexWrap: "wrap",
    flexDirection: "row",
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#FF3276",
    backgroundColor: "#fff",
  },
  checkboxContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 8,
  },
  checkboxLabel: {
    fontSize: 14,
    color: "#FF3276",
  },
  precoContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  precos: {
    width: "45%",
  },
  precoText: {
    color: "#FF3276",
    fontWeight: "500",
  },
  input: {
    borderWidth: 1,
    borderColor: "#FF3276",
    marginVertical: 8,
    padding: 4,
    backgroundColor: "#f5f5f5",
  },
  botoesFiltro: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingBottom: 8,
  },
  botaoPress: {
    backgroundColor: "#FF3276",
    justifyContent: "center",
    alignItems: "center",
    padding: 10,
    borderRadius: 8,
    marginBottom: 4,
    width: 150,
  },
  textoBotao: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  card: {
    flexDirection: "row",
    backgroundColor: "#F5F5F5",
    borderRadius: 24,
    marginBottom: 25,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
    marginHorizontal: 8,
    borderColor: "#FF3276",
    borderWidth: 1.5,
  },
  imgContainer: {
    marginTop: 8,
  },
  precoJogo: {
    fontSize: 16,
    paddingVertical: 12,
    color: "#FF3276",
    fontWeight: "500",
    paddingHorizontal: 20,
    backgroundColor: "#F5F5F5",
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 24,
    borderTopColor: "#FF3276",
    borderTopWidth: 1.5,
    borderRightColor: "#FF3276",
    borderRightWidth: 1.5,
  },
  cardTitle: {
    backgroundColor: "#FF3276",
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 20,
    alignContent: "center",
    justifyContent: "center",
  },
  nomeJogo: {
    fontSize: 20,
    fontWeight: "bold",
    paddingVertical: 8,
    paddingLeft: 12,
    color: "#fff",
    width: "100%",
  },

  botoesContainer: {
    flex: 1,
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 20,
  },
  botao: {
    backgroundColor: "#FF3276",
    justifyContent: "center",
    alignItems: "center",
    padding: 10,
    borderRadius: 8,
    width: 120,
    boxShadow: "2px 2px 2px rgba(0, 0, 0, 0.25)",
  },
  imagem: {
    width: 190,
    height: 200,
    borderRadius: 16,
    marginHorizontal: 8,
    borderColor: "#FF3276",
    borderWidth: 1.5,
    marginBottom: 8,
  },
  conteudoCard: {
    flex: 1,
  },
});
